spring:
  profiles:
    active:
      -dev

---

spring:
  profiles: dev  # 开发环境
  application:
    name: microservicecloud-config-sef-dev

---
spring:
  profiles: test # 测试环境
  application:
    name: microservicecloud-config-sef-test

# 请保存为UTF-8格式